// src/app/auth/signup/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { trpc } from '@/lib/trpc/client'
import { Card, CardBody, CardHeader, Input, Button, Select, SelectItem } from '@heroui/react'
import Link from 'next/link'

export default function SignupPage() {
  const router = useRouter()
  const [error, setError] = useState('')
  const signupMutation = trpc.auth.signup.useMutation()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setError('')

    const formData = new FormData(e.currentTarget)
    const password = formData.get('password') as string
    const confirmPassword = formData.get('confirmPassword') as string

    if (password !== confirmPassword) {
      setError('Passwords do not match')
      return
    }

    try {
      const result = await signupMutation.mutateAsync({
        email: formData.get('email') as string,
        password,
        full_name: formData.get('full_name') as string,
        display_name: formData.get('display_name') as string,
        role: (formData.get('role') as 'admin' | 'agent' | 'internal_admin') || 'agent',
      })

      if (result.success) {
        alert('Account created successfully! Please check your email to verify your account.')
        router.push('/')
      }
    } catch (err: any) {
      setError(err.message || 'Failed to create account')
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="flex flex-col items-center gap-2 pb-6">
          <h1 className="text-3xl font-bold text-primary">LoanStar</h1>
          <p className="text-lg font-semibold">Create Account</p>
        </CardHeader>
        <CardBody>
          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <Input
              label="Full Name"
              name="full_name"
              placeholder="Enter your full name"
              required
            />

            <Input
              label="Display Name (Optional)"
              name="display_name"
              placeholder="How you'd like to be called"
            />

            <Input
              label="Email"
              name="email"
              type="email"
              placeholder="Enter your email"
              required
            />

            <Input
              label="Password"
              name="password"
              type="password"
              placeholder="Enter your password"
              required
              description="Minimum 6 characters"
            />

            <Input
              label="Confirm Password"
              name="confirmPassword"
              type="password"
              placeholder="Confirm your password"
              required
            />

            <Select
              label="Role"
              name="role"
              placeholder="Select your role"
              defaultSelectedKeys={['agent']}
              required
            >
              <SelectItem key="agent" value="agent">
                Agent
              </SelectItem>
              <SelectItem key="admin" value="admin">
                Admin
              </SelectItem>
              <SelectItem key="internal_admin" value="internal_admin">
                Internal Admin
              </SelectItem>
            </Select>

            {error && (
              <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-sm text-red-600">{error}</p>
              </div>
            )}

            <Button
              type="submit"
              color="primary"
              isLoading={signupMutation.isPending}
              fullWidth
            >
              Create Account
            </Button>

            <div className="text-center">
              <p className="text-sm text-gray-600">
                Already have an account?{' '}
                <Link href="/" className="text-primary font-semibold hover:underline">
                  Login
                </Link>
              </p>
            </div>
          </form>
        </CardBody>
      </Card>
    </div>
  )
}

// pages/auth/signup.vue
<template>
  <v-container class="fill-height flat-auth-container" fluid>
    <v-row align="center" justify="center" class="ma-0">
      <v-col cols="12" sm="10" md="6" lg="5" class="pa-8">
        <!-- Header -->
        <div class="text-center mb-8">
          <h1 class="text-h3 font-weight-bold text-white mb-3">
            Create Account
          </h1>
          <p class="text-body-1 text-grey-lighten-1">
            Join LoanStar
          </p>
        </div>

        <!-- Signup Form -->
        <v-form ref="formRef" v-model="formValid" @submit.prevent="handleSignup">
          <v-text-field
            v-model="form.full_name"
            label="Full Name"
            prepend-inner-icon="mdi-account"
            :rules="[rules.required]"
            variant="outlined"
            flat
            color="white"
            class="mb-4 white-input"
            hide-details="auto"
            density="comfortable"
            autocomplete="off"
          />

          <v-text-field
            v-model="form.email"
            label="Email"
            type="email"
            prepend-inner-icon="mdi-email"
            :rules="[rules.required, rules.email]"
            variant="outlined"
            flat
            color="white"
            class="mb-4 white-input"
            hide-details="auto"
            density="comfortable"
            autocomplete="username"
          />

          <v-text-field
            v-model="form.password"
            label="Password"
            :type="showPassword ? 'text' : 'password'"
            prepend-inner-icon="mdi-lock"
            :append-inner-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
            :rules="[rules.required, rules.password]"
            variant="outlined"
            flat
            color="white"
            class="mb-4 white-input"
            hide-details="auto"
            density="comfortable"
            autocomplete="new-password"
            @click:append-inner="showPassword = !showPassword"
          />

          <v-text-field
            v-model="form.confirmPassword"
            label="Confirm Password"
            :type="showConfirmPassword ? 'text' : 'password'"
            prepend-inner-icon="mdi-lock-check"
            :append-inner-icon="showConfirmPassword ? 'mdi-eye' : 'mdi-eye-off'"
            :rules="[rules.required, rules.passwordMatch]"
            variant="outlined"
            flat
            color="white"
            class="mb-4 white-input"
            hide-details="auto"
            density="comfortable"
            autocomplete="new-password"
            @click:append-inner="showConfirmPassword = !showConfirmPassword"
          />

          <v-alert v-if="error" type="error" variant="tonal" class="mb-4 error-alert">
            {{ error }}
          </v-alert>

          <v-alert v-if="success" type="success" variant="tonal" class="mb-4 success-alert">
            Account created successfully! Redirecting to login...
          </v-alert>

          <v-btn
            type="submit"
            color="white"
            size="x-large"
            block
            flat
            :loading="loading"
            :disabled="!formValid"
            class="mb-6 text-none font-weight-bold signup-btn"
          >
            Sign Up
          </v-btn>

          <div class="text-center">
            <span class="text-body-2 text-grey-lighten-1">Already have an account?</span>
            <v-btn variant="text" size="small" to="/auth/login" class="text-none text-white ml-1">
              Login
            </v-btn>
          </div>
        </v-form>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'admin'
})

const formRef = ref()
const formValid = ref(false)
const showPassword = ref(false)
const showConfirmPassword = ref(false)
const loading = ref(false)
const error = ref('')
const success = ref(false)

const form = reactive({
  full_name: '',
  email: '',
  password: '',
  confirmPassword: '',
  role: 'agent' as 'admin' | 'agent'
})

const rules = {
  required: (v: string) => !!v || 'Field is required',
  email: (v: string) => /.+@.+\..+/.test(v) || 'E-mail must be valid',
  password: (v: string) => v.length >= 6 || 'Password must be at least 6 characters',
  passwordMatch: (v: string) => v === form.password || 'Passwords must match'
}

const { signup } = useAuth()
const router = useRouter()

const handleSignup = async () => {
  if (!formRef.value) { return }

  const { valid } = await formRef.value.validate()
  if (!valid) { return }

  loading.value = true
  error.value = ''
  success.value = false

  const result = await signup({
    email: form.email,
    password: form.password,
    full_name: form.full_name,
    role: form.role
  })

  if (result.success) {
    success.value = true
    setTimeout(() => {
      router.push('/auth/login')
    }, 2000)
  } else {
    error.value = result.error || 'Signup failed'
  }

  loading.value = false
}
</script>

<style scoped>
.flat-auth-container {
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
  min-height: 100vh;
}

.flat-auth-container .v-col {
  background: transparent;
  border-radius: 0;
  max-width: 550px;
}

/* White input styling */
:deep(.white-input .v-field) {
  background-color: rgba(255, 255, 255, 0.15) !important;
}

:deep(.white-input .v-field__input) {
  color: white !important;
  opacity: 1;
}

:deep(.white-input .v-field__input::placeholder) {
  color: rgba(255, 255, 255, 0.5) !important;
}

:deep(.white-input .v-label) {
  color: rgba(255, 255, 255, 0.8) !important;
}

:deep(.white-input .v-field--focused .v-label) {
  color: white !important;
}

:deep(.white-input .v-field__prepend-inner),
:deep(.white-input .v-field__append-inner) {
  color: rgba(255, 255, 255, 0.8) !important;
}

:deep(.white-input .v-messages__message) {
  color: rgba(255, 255, 255, 0.8);
}

/* Signup button */
.signup-btn {
  background: white !important;
  color: #1a1a2e !important;
  letter-spacing: 0.5px;
}

.signup-btn:hover {
  background: rgba(255, 255, 255, 0.9) !important;
}

/* Error alert */
:deep(.error-alert) {
  background-color: rgba(244, 67, 54, 0.2) !important;
  color: white !important;
}

:deep(.error-alert .v-alert__content) {
  color: white !important;
}

/* Success alert */
:deep(.success-alert) {
  background-color: rgba(76, 175, 80, 0.2) !important;
  color: white !important;
}

:deep(.success-alert .v-alert__content) {
  color: white !important;
}

@media (max-width: 600px) {
  .flat-auth-container .v-col {
    border-radius: 0;
    min-height: 100vh;
  }
}
</style>
