// src/app/accounts/[id]/page.tsx
'use client'

import { use } from 'react'
import { trpc } from '@/lib/trpc/client'
import { useRouter } from 'next/navigation'
import { Card, CardBody, CardHeader, Button, Chip, Divider } from '@heroui/react'
import { formatDate, formatCurrency } from '@/utils/formatters'
import Link from 'next/link'

export default function AccountDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()
  const { data: account, isLoading } = trpc.accounts.getById.useQuery({ id })

  if (isLoading) {
    return <div>Loading...</div>
  }

  if (!account) {
    return <div>Account not found</div>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="light" onPress={() => router.back()}>
          ← Back
        </Button>
        <h1 className="text-3xl font-bold">{account.name}</h1>
        <Chip
          color={
            account.status === 'active'
              ? 'success'
              : account.status === 'suspended'
              ? 'danger'
              : 'default'
          }
        >
          {account.status}
        </Chip>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <h2 className="text-xl font-semibold">Personal Information</h2>
          </CardHeader>
          <CardBody className="space-y-3">
            <div>
              <p className="text-sm text-gray-600">Full Name</p>
              <p className="font-medium">{account.name}</p>
            </div>
            {account.date_of_birth && (
              <div>
                <p className="text-sm text-gray-600">Date of Birth</p>
                <p className="font-medium">{formatDate(account.date_of_birth)}</p>
              </div>
            )}
            {account.contact_info && (
              <div>
                <p className="text-sm text-gray-600">Contact Info</p>
                <p className="font-medium">{account.contact_info}</p>
              </div>
            )}
            {account.address && (
              <div>
                <p className="text-sm text-gray-600">Address</p>
                <p className="font-medium">{account.address}</p>
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader>
            <h2 className="text-xl font-semibold">Identification</h2>
          </CardHeader>
          <CardBody className="space-y-3">
            {account.government_id_type && (
              <div>
                <p className="text-sm text-gray-600">Government ID Type</p>
                <p className="font-medium">{account.government_id_type}</p>
              </div>
            )}
            {account.government_id_number && (
              <div>
                <p className="text-sm text-gray-600">Government ID Number</p>
                <p className="font-medium">{account.government_id_number}</p>
              </div>
            )}
            {account.ssn_tax_id && (
              <div>
                <p className="text-sm text-gray-600">SSN / Tax ID</p>
                <p className="font-medium">{account.ssn_tax_id}</p>
              </div>
            )}
          </CardBody>
        </Card>
      </div>

      <Card>
        <CardHeader className="flex justify-between items-center">
          <h2 className="text-xl font-semibold">Loans</h2>
          <Link href={`/loans/create?accountId=${account.id}`}>
            <Button color="primary" size="sm">
              Create Loan
            </Button>
          </Link>
        </CardHeader>
        <Divider />
        <CardBody>
          {account.loans && account.loans.length > 0 ? (
            <div className="space-y-3">
              {account.loans.map((loan: any) => (
                <Link key={loan.id} href={`/loans/${loan.id}`}>
                  <div className="p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium">
                          {formatCurrency(loan.principal_amount)}
                        </p>
                        <p className="text-sm text-gray-600">
                          {loan.tenure_months} months @ {loan.interest_rate}%
                        </p>
                      </div>
                      <Chip
                        size="sm"
                        color={
                          loan.status === 'active'
                            ? 'success'
                            : loan.status === 'pending_approval'
                            ? 'warning'
                            : 'default'
                        }
                      >
                        {loan.status.replace('_', ' ')}
                      </Chip>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          ) : (
            <p className="text-gray-500 text-center py-8">No loans yet</p>
          )}
        </CardBody>
      </Card>
    </div>
  )
}

// pages/accounts/[id].vue
<template>
  <v-container fluid>
    <!-- Loading State -->
    <v-row v-if="accountsStore.loading" class="mt-8">
      <v-col cols="12" class="text-center">
        <v-progress-circular indeterminate color="primary" size="64" />
        <p class="mt-4 text-grey">Loading account details...</p>
      </v-col>
    </v-row>

    <!-- Account Details -->
    <template v-else-if="account">
      <v-row>
        <v-col cols="12">
          <div class="d-flex align-center mb-4">
            <v-btn icon variant="text" @click="$router.back()">
              <v-icon>mdi-arrow-left</v-icon>
            </v-btn>
            <div class="ml-4">
              <h1 class="text-h4">{{ account.name }}</h1>
              <v-chip :color="getStatusColor(account.status)" size="small" class="mt-2">
                {{ account.status }}
              </v-chip>
            </div>
          </div>
        </v-col>
      </v-row>

      <v-row>
        <!-- Account Information -->
        <v-col cols="12" md="4">
          <v-card>
            <v-card-title>Account Information</v-card-title>
            <v-divider />
            <v-card-text>
              <div class="mb-4">
                <div class="text-caption text-grey mb-1">Contact Information</div>
                <div class="d-flex align-center">
                  <v-icon size="small" class="mr-2">mdi-phone</v-icon>
                  <span>{{ account.contact_info }}</span>
                </div>
              </div>

              <div class="mb-4">
                <div class="text-caption text-grey mb-1">Address</div>
                <div class="d-flex align-start">
                  <v-icon size="small" class="mr-2 mt-1">mdi-map-marker</v-icon>
                  <span>{{ account.address }}</span>
                </div>
              </div>

              <div class="mb-4">
                <div class="text-caption text-grey mb-1">Assigned Agent</div>
                <div class="d-flex align-center">
                  <v-icon size="small" class="mr-2">mdi-account</v-icon>
                  <span>{{ account.assigned_agent?.full_name || 'N/A' }}</span>
                </div>
              </div>

              <div class="mb-4">
                <div class="text-caption text-grey mb-1">Created</div>
                <div class="d-flex align-center">
                  <v-icon size="small" class="mr-2">mdi-calendar</v-icon>
                  <span>{{ formatDate(account.created_at) }}</span>
                </div>
              </div>

              <v-btn
                v-if="account.id_proof_url"
                block
                variant="outlined"
                prepend-icon="mdi-file-image"
                :href="account.id_proof_url"
                target="_blank"
              >
                View ID Proof
              </v-btn>
            </v-card-text>
            <v-card-actions>
              <v-btn
                block
                color="primary"
                prepend-icon="mdi-file-document-plus"
                :to="`/loans/create?account_id=${account.id}`"
              >
                Create Loan
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>

        <!-- Loans List -->
        <v-col cols="12" md="8">
          <v-card>
            <v-card-title class="d-flex justify-space-between align-center">
              <span>Loans ({{ account.loans?.length || 0 }})</span>
              <v-btn
                size="small"
                color="primary"
                prepend-icon="mdi-plus"
                :to="`/loans/create?account_id=${account.id}`"
              >
                New Loan
              </v-btn>
            </v-card-title>
            <v-divider />

            <v-list v-if="account.loans && account.loans.length > 0">
              <v-list-item
                v-for="loan in account.loans"
                :key="loan.id"
                :to="`/loans/${loan.id}`"
              >
                <template #prepend>
                  <v-avatar :color="getLoanStatusColor(loan.status)">
                    <v-icon>mdi-file-document</v-icon>
                  </v-avatar>
                </template>

                <v-list-item-title>
                  {{ formatCurrency(loan.principal_amount) }}
                </v-list-item-title>
                <v-list-item-subtitle>
                  {{ loan.interest_rate }}% • {{ loan.payment_frequency }} • {{ loan.tenure_months }} months
                </v-list-item-subtitle>

                <template #append>
                  <div class="text-right">
                    <v-chip :color="getLoanStatusColor(loan.status)" size="small">
                      {{ loan.status }}
                    </v-chip>
                    <div class="text-caption text-grey mt-1">
                      Balance: {{ formatCurrency(loan.current_balance) }}
                    </div>
                  </div>
                </template>
              </v-list-item>
            </v-list>

            <v-card-text v-else class="text-center text-grey py-8">
              <v-icon size="64" color="grey-lighten-2">mdi-file-document-outline</v-icon>
              <p class="mt-4">No loans yet</p>
              <v-btn
                color="primary"
                prepend-icon="mdi-plus"
                :to="`/loans/create?account_id=${account.id}`"
                class="mt-2"
              >
                Create First Loan
              </v-btn>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </template>

    <!-- Error State -->
    <v-row v-else class="mt-8">
      <v-col cols="12" class="text-center">
        <v-icon size="120" color="error">mdi-alert-circle-outline</v-icon>
        <h3 class="text-h6 mt-4">Account not found</h3>
        <v-btn color="primary" class="mt-4" @click="$router.back()">
          Go Back
        </v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { formatCurrency, formatDate } from '~/utils/formatters'

definePageMeta({
  middleware: 'auth'
})

const route = useRoute()
const accountsStore = useAccounts()
const uiStore = useUI()

const account = computed(() => accountsStore.selectedAccount)

const getStatusColor = (status: string) => {
  const colors: Record<string, string> = {
    active: 'success',
    inactive: 'grey',
    suspended: 'error'
  }
  return colors[status] || 'grey'
}

const getLoanStatusColor = (status: string) => {
  const colors: Record<string, string> = {
    pending_approval: 'warning',
    approved: 'info',
    active: 'success',
    closed: 'grey',
    rejected: 'error'
  }
  return colors[status] || 'grey'
}

// Fetch account details on mount
onMounted(async () => {
  try {
    await accountsStore.fetchAccountById(route.params.id as string)
  } catch (error: any) {
    uiStore.showError('Failed to load account details')
  }
})
</script>
