// src/app/loans/[id]/page.tsx
'use client'

import { use } from 'react'
import { trpc } from '@/lib/trpc/client'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import { useAmortization } from '@/hooks/useAmortization'
import { useLoanPenalties } from '@/hooks/usePenalties'
import {
  Card,
  CardBody,
  CardHeader,
  Button,
  Chip,
  Divider,
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
} from '@heroui/react'
import { formatDate, formatCurrency } from '@/utils/formatters'
import Link from 'next/link'

export default function LoanDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()
  const { user, isAdmin } = useAuth()
  const { data: loan, isLoading, refetch } = trpc.loans.getById.useQuery({ id })
  const approveMutation = trpc.loans.approve.useMutation({
    onSuccess: () => refetch(),
  })
  const rejectMutation = trpc.loans.reject.useMutation({
    onSuccess: () => refetch(),
  })

  const amortization = useAmortization({
    principalAmount: loan?.principal_amount || 0,
    interestRate: loan?.interest_rate || 0,
    tenureMonths: loan?.tenure_months || 0,
    paymentFrequency: loan?.payment_frequency || 'monthly',
    startDate: loan?.start_date || new Date().toISOString(),
  })

  const penalties = useLoanPenalties({
    amortizationSchedule: loan?.amortization_schedule || [],
    payments: (loan as any)?.payments || [],
  })

  if (isLoading) {
    return <div>Loading...</div>
  }

  if (!loan) {
    return <div>Loan not found</div>
  }

  const handleApprove = async () => {
    if (confirm('Are you sure you want to approve this loan?')) {
      await approveMutation.mutateAsync({ id })
    }
  }

  const handleReject = async () => {
    const reason = prompt('Please provide a reason for rejection:')
    if (reason) {
      await rejectMutation.mutateAsync({ id, reason })
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="light" onPress={() => router.back()}>
            ← Back
          </Button>
          <h1 className="text-3xl font-bold">Loan Details</h1>
          <Chip
            color={
              loan.status === 'active'
                ? 'success'
                : loan.status === 'pending_approval'
                ? 'warning'
                : loan.status === 'rejected'
                ? 'danger'
                : 'default'
            }
          >
            {loan.status.replace('_', ' ').toUpperCase()}
          </Chip>
        </div>

        {isAdmin && loan.status === 'pending_approval' && (
          <div className="flex gap-2">
            <Button
              color="success"
              onPress={handleApprove}
              isLoading={approveMutation.isPending}
            >
              Approve
            </Button>
            <Button
              color="danger"
              variant="flat"
              onPress={handleReject}
              isLoading={rejectMutation.isPending}
            >
              Reject
            </Button>
          </div>
        )}
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card>
          <CardHeader>
            <h2 className="text-lg font-semibold">Loan Information</h2>
          </CardHeader>
          <CardBody className="space-y-3">
            <div>
              <p className="text-sm text-gray-600">Principal Amount</p>
              <p className="text-2xl font-bold">{formatCurrency(loan.principal_amount)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Interest Rate</p>
              <p className="font-medium">{loan.interest_rate}% per month</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Tenure</p>
              <p className="font-medium">{loan.tenure_months} months</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Payment Frequency</p>
              <p className="font-medium">{loan.payment_frequency}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Start Date</p>
              <p className="font-medium">{formatDate(loan.start_date)}</p>
            </div>
          </CardBody>
        </Card>

        <Card>
          <CardHeader>
            <h2 className="text-lg font-semibold">Financial Summary</h2>
          </CardHeader>
          <CardBody className="space-y-3">
            <div>
              <p className="text-sm text-gray-600">EMI Amount</p>
              <p className="text-2xl font-bold">{formatCurrency(amortization.emi)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Total Interest</p>
              <p className="font-medium">{formatCurrency(amortization.totalInterest)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Total Payment</p>
              <p className="font-medium">{formatCurrency(amortization.totalPayment)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Number of Payments</p>
              <p className="font-medium">{amortization.numPayments}</p>
            </div>
          </CardBody>
        </Card>

        <Card>
          <CardHeader>
            <h2 className="text-lg font-semibold">Payment Status</h2>
          </CardHeader>
          <CardBody className="space-y-3">
            <div>
              <p className="text-sm text-gray-600">Current Balance</p>
              <p className="text-2xl font-bold">{formatCurrency(loan.current_balance)}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Total Paid</p>
              <p className="font-medium text-green-600">
                {formatCurrency(loan.total_paid)}
              </p>
            </div>
            <div>
              <p className="text-sm text-gray-600">Total Penalties</p>
              <p className="font-medium text-red-600">
                {formatCurrency(penalties.totalPenalties)}
              </p>
            </div>
            {penalties.totalOverdue > 0 && (
              <div>
                <p className="text-sm text-gray-600">Amount Overdue</p>
                <p className="font-medium text-red-600">
                  {formatCurrency(penalties.totalOverdue)}
                </p>
              </div>
            )}
          </CardBody>
        </Card>
      </div>

      {loan.rejection_reason && (
        <Card className="border-2 border-danger">
          <CardHeader>
            <h2 className="text-lg font-semibold text-danger">Rejection Reason</h2>
          </CardHeader>
          <CardBody>
            <p>{loan.rejection_reason}</p>
          </CardBody>
        </Card>
      )}

      <Card>
        <CardHeader className="flex justify-between items-center">
          <h2 className="text-xl font-semibold">Amortization Schedule</h2>
          <Link href={`/payments/create?loanId=${loan.id}`}>
            <Button color="primary" size="sm">
              Record Payment
            </Button>
          </Link>
        </CardHeader>
        <Divider />
        <CardBody>
          <Table aria-label="Amortization schedule">
            <TableHeader>
              <TableColumn>#</TableColumn>
              <TableColumn>DUE DATE</TableColumn>
              <TableColumn>PRINCIPAL</TableColumn>
              <TableColumn>INTEREST</TableColumn>
              <TableColumn>TOTAL DUE</TableColumn>
              <TableColumn>BALANCE</TableColumn>
            </TableHeader>
            <TableBody>
              {amortization.schedule.map((item) => (
                <TableRow key={item.payment_number}>
                  <TableCell>{item.payment_number}</TableCell>
                  <TableCell>{formatDate(item.due_date)}</TableCell>
                  <TableCell>{formatCurrency(item.principal_due)}</TableCell>
                  <TableCell>{formatCurrency(item.interest_due)}</TableCell>
                  <TableCell className="font-semibold">
                    {formatCurrency(item.total_due)}
                  </TableCell>
                  <TableCell>{formatCurrency(item.remaining_balance)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardBody>
      </Card>

      {penalties.penaltiesByPayment.length > 0 && (
        <Card className="border-2 border-warning">
          <CardHeader>
            <h2 className="text-xl font-semibold text-warning">Penalties</h2>
          </CardHeader>
          <Divider />
          <CardBody>
            <Table aria-label="Penalties breakdown">
              <TableHeader>
                <TableColumn>PAYMENT #</TableColumn>
                <TableColumn>DUE DATE</TableColumn>
                <TableColumn>DAYS OVERDUE</TableColumn>
                <TableColumn>AMOUNT DUE</TableColumn>
                <TableColumn>AMOUNT PAID</TableColumn>
                <TableColumn>PENALTY</TableColumn>
              </TableHeader>
              <TableBody>
                {penalties.penaltiesByPayment.map((penalty) => (
                  <TableRow key={penalty.paymentNumber}>
                    <TableCell>{penalty.paymentNumber}</TableCell>
                    <TableCell>{formatDate(penalty.dueDate)}</TableCell>
                    <TableCell className="text-red-600">{penalty.daysOverdue} days</TableCell>
                    <TableCell>{formatCurrency(penalty.amountDue)}</TableCell>
                    <TableCell>{formatCurrency(penalty.amountPaid)}</TableCell>
                    <TableCell className="font-semibold text-red-600">
                      {formatCurrency(penalty.penaltyAmount)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardBody>
        </Card>
      )}
    </div>
  )
}

// pages/loans/[id].vue
<template>
  <v-container fluid>
    <!-- Loading State -->
    <v-row v-if="loading" class="mt-8">
      <v-col cols="12" class="text-center">
        <v-progress-circular indeterminate color="primary" size="64" />
        <p class="mt-4 text-grey">
          Loading loan details...
        </p>
      </v-col>
    </v-row>

    <!-- Loan Details -->
    <template v-else-if="loan">
      <v-row>
        <v-col cols="12">
          <div class="d-flex align-center mb-4">
            <v-btn icon variant="text" @click="$router.back()">
              <v-icon>mdi-arrow-left</v-icon>
            </v-btn>
            <div class="ml-4 flex-grow-1">
              <h1 class="text-h4">
                {{ formatCurrency(loan.principal_amount) }} Loan
              </h1>
              <p class="text-subtitle-1">
                {{ loan.account?.name }}
              </p>
            </div>
            <v-chip :color="getLoanStatusColor(loan.status)" size="large">
              {{ loan.status.replace('_', ' ').toUpperCase() }}
            </v-chip>
          </div>
        </v-col>
      </v-row>

      <v-row>
        <!-- Loan Summary -->
        <v-col cols="12" md="4">
          <v-card class="mb-4">
            <v-card-title>Loan Summary</v-card-title>
            <v-divider />
            <v-card-text>
              <div class="mb-3">
                <div class="text-caption text-grey">
                  Principal Amount
                </div>
                <div class="text-h6">
                  {{ formatCurrency(loan.principal_amount) }}
                </div>
              </div>
              <div class="mb-3">
                <div class="text-caption text-grey">
                  Current Balance
                </div>
                <div class="text-h6" :class="loan.current_balance > 0 ? 'text-warning' : 'text-success'">
                  {{ formatCurrency(loan.current_balance) }}
                </div>
              </div>
              <div class="mb-3">
                <div class="text-caption text-grey">
                  Total Paid
                </div>
                <div class="text-h6 text-success">
                  {{ formatCurrency(loan.total_paid) }}
                </div>
              </div>
              <div v-if="loan.total_penalties > 0" class="mb-3">
                <div class="text-caption text-grey">
                  Total Penalties
                </div>
                <div class="text-h6 text-error">
                  {{ formatCurrency(loan.total_penalties) }}
                </div>
              </div>
              <v-divider class="my-3" />
              <div class="mb-2">
                <v-icon size="small" class="mr-2">
                  mdi-percent
                </v-icon>
                <span>{{ loan.interest_rate }}% per month</span>
              </div>
              <div class="mb-2">
                <v-icon size="small" class="mr-2">
                  mdi-calendar
                </v-icon>
                <span>{{ loan.tenure_months }} months</span>
              </div>
              <div class="mb-2">
                <v-icon size="small" class="mr-2">
                  mdi-calendar-clock
                </v-icon>
                <span>{{ loan.payment_frequency }}</span>
              </div>
              <div class="mb-2">
                <v-icon size="small" class="mr-2">
                  mdi-calendar-start
                </v-icon>
                <span>{{ formatDate(loan.start_date) }}</span>
              </div>
              <div>
                <v-icon size="small" class="mr-2">
                  mdi-calendar-end
                </v-icon>
                <span>{{ formatDate(loan.end_date) }}</span>
              </div>
            </v-card-text>
            <v-card-actions v-if="loan.status === 'active'">
              <v-btn
                block
                color="primary"
                prepend-icon="mdi-cash-plus"
                :to="`/payments/create?loan_id=${loan.id}`"
              >
                Record Payment
              </v-btn>
            </v-card-actions>
          </v-card>

          <!-- Admin Actions -->
          <v-card v-if="authStore.isAdmin && loan.status === 'pending_approval'" class="mb-4">
            <v-card-title>Admin Actions</v-card-title>
            <v-divider />
            <v-card-text>
              <v-btn
                block
                color="success"
                prepend-icon="mdi-check"
                class="mb-2"
                @click="approveLoanDialog = true"
              >
                Approve Loan
              </v-btn>
              <v-btn
                block
                color="error"
                prepend-icon="mdi-close"
                variant="outlined"
                @click="rejectLoanDialog = true"
              >
                Reject Loan
              </v-btn>
            </v-card-text>
          </v-card>
        </v-col>

        <!-- Amortization Schedule -->
        <v-col cols="12" md="8">
          <v-card>
            <v-card-title class="d-flex justify-space-between align-center">
              <span>Amortization Schedule</span>
              <v-btn size="small" variant="outlined" prepend-icon="mdi-download">
                Export
              </v-btn>
            </v-card-title>
            <v-divider />
            <div style="overflow-x: auto;">
              <v-table density="compact">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Due Date</th>
                    <th>Principal</th>
                    <th>Interest</th>
                    <th>Total Due</th>
                    <th>Balance</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    v-for="item in loan.amortization_schedule"
                    :key="item.payment_number"
                    :class="getScheduleRowClass(item)"
                  >
                    <td>{{ item.payment_number }}</td>
                    <td>{{ formatDate(item.due_date) }}</td>
                    <td>{{ formatCurrency(item.principal_due) }}</td>
                    <td>{{ formatCurrency(item.interest_due) }}</td>
                    <td class="font-weight-bold">
                      {{ formatCurrency(item.total_due) }}
                    </td>
                    <td>{{ formatCurrency(item.remaining_balance) }}</td>
                    <td>
                      <v-chip size="x-small" :color="getPaymentStatusColor(item)">
                        {{ getPaymentStatus(item) }}
                      </v-chip>
                    </td>
                  </tr>
                </tbody>
              </v-table>
            </div>
          </v-card>

          <!-- Payment History -->
          <v-card class="mt-4">
            <v-card-title>Payment History ({{ loan.payments?.length || 0 }})</v-card-title>
            <v-divider />
            <v-list v-if="loan.payments && loan.payments.length > 0">
              <v-list-item v-for="payment in loan.payments" :key="payment.id">
                <template #prepend>
                  <v-avatar color="success">
                    <v-icon>mdi-cash</v-icon>
                  </v-avatar>
                </template>
                <v-list-item-title>{{ formatCurrency(payment.amount) }}</v-list-item-title>
                <v-list-item-subtitle>
                  {{ formatDate(payment.payment_date) }} •
                  Principal: {{ formatCurrency(payment.applied_to_principal) }} •
                  Interest: {{ formatCurrency(payment.applied_to_interest) }}
                  <span v-if="payment.applied_to_penalty > 0">
                    • Penalty: {{ formatCurrency(payment.applied_to_penalty) }}
                  </span>
                </v-list-item-subtitle>
              </v-list-item>
            </v-list>
            <v-card-text v-else class="text-center text-grey py-8">
              No payments recorded yet
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </template>

    <!-- Error State -->
    <v-row v-else class="mt-8">
      <v-col cols="12" class="text-center">
        <v-icon size="120" color="error">
          mdi-alert-circle-outline
        </v-icon>
        <h3 class="text-h6 mt-4">
          Loan not found
        </h3>
        <v-btn color="primary" class="mt-4" @click="$router.back()">
          Go Back
        </v-btn>
      </v-col>
    </v-row>

    <!-- Approve Dialog -->
    <v-dialog v-model="approveLoanDialog" max-width="400">
      <v-card>
        <v-card-title>Approve Loan</v-card-title>
        <v-card-text>
          Are you sure you want to approve this loan?
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="approveLoanDialog = false">
            Cancel
          </v-btn>
          <v-btn color="success" :loading="actionLoading" @click="handleApproveLoan">
            Approve
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Reject Dialog -->
    <v-dialog v-model="rejectLoanDialog" max-width="500">
      <v-card>
        <v-card-title>Reject Loan</v-card-title>
        <v-card-text>
          <v-textarea
            v-model="rejectionReason"
            label="Reason for rejection"
            rows="3"
            variant="outlined"
          />
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="rejectLoanDialog = false">
            Cancel
          </v-btn>
          <v-btn
            color="error"
            :loading="actionLoading"
            :disabled="!rejectionReason"
            @click="handleRejectLoan"
          >
            Reject
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup lang="ts">
import { formatCurrency, formatDate, isPastDue } from '~/utils/formatters'
import type { AmortizationScheduleItem } from '~/types'

definePageMeta({
  middleware: 'auth'
})

const route = useRoute()
const router = useRouter()
const authStore = useAuth()
const loansStore = useLoans()
const { loading } = loansStore
const uiStore = useUI()

const approveLoanDialog = ref(false)
const rejectLoanDialog = ref(false)
const rejectionReason = ref('')
const actionLoading = ref(false)

const loan = computed(() => loansStore.selectedLoan)

const getLoanStatusColor = (status: string) => {
  const colors: Record<string, string> = {
    pending_approval: 'warning',
    approved: 'info',
    active: 'success',
    closed: 'grey',
    rejected: 'error'
  }
  return colors[status] || 'grey'
}

const getScheduleRowClass = (item: AmortizationScheduleItem) => {
  if (loan.value) {
    const totalDue = loan.value.amortization_schedule
      .slice(0, item.payment_number)
      .reduce((sum, i) => sum + i.total_due, 0)

    if (loan.value.total_paid >= totalDue) {
      return 'bg-success-lighten-5'
    } else if (isPastDue(item.due_date)) {
      return 'bg-error-lighten-5'
    }
  }
  return ''
}

const getPaymentStatus = (item: AmortizationScheduleItem) => {
  if (loan.value) {
    const totalDue = loan.value.amortization_schedule
      .slice(0, item.payment_number)
      .reduce((sum, i) => sum + i.total_due, 0)

    if (loan.value.total_paid >= totalDue) {
      return 'Paid'
    } else if (isPastDue(item.due_date)) {
      return 'Overdue'
    } else {
      return 'Pending'
    }
  }
  return 'Pending'
}

const getPaymentStatusColor = (item: AmortizationScheduleItem) => {
  const status = getPaymentStatus(item)
  return status === 'Paid' ? 'success' : status === 'Overdue' ? 'error' : 'grey'
}

const handleApproveLoan = async () => {
  actionLoading.value = true
  const result = await loansStore.approveLoan(loan.value!.id)

  if (result.success) {
    uiStore.showSuccess('Loan approved successfully')
    approveLoanDialog.value = false
    await loansStore.fetchLoanById(route.params.id as string)
  } else {
    uiStore.showError(result.error || 'Failed to approve loan')
  }

  actionLoading.value = false
}

const handleRejectLoan = async () => {
  actionLoading.value = true
  const result = await loansStore.rejectLoan(loan.value!.id, rejectionReason.value)

  if (result.success) {
    uiStore.showSuccess('Loan rejected')
    rejectLoanDialog.value = false
    router.push('/loans')
  } else {
    uiStore.showError(result.error || 'Failed to reject loan')
  }

  actionLoading.value = false
}

// Fetch loan details on mount
onMounted(async () => {
  try {
    await loansStore.fetchLoanById(route.params.id as string)
  } catch (error: any) {
    uiStore.showError('Failed to load loan details')
  }
})
</script>
