// src/app/loans/create/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { trpc } from '@/lib/trpc/client'
import { Card, CardBody, CardHeader, Input, Button, Select, SelectItem } from '@heroui/react'

export default function CreateLoanPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const accountId = searchParams.get('accountId')
  const [selectedAccountId, setSelectedAccountId] = useState(accountId || '')

  const { data: accounts } = trpc.accounts.getAll.useQuery()
  const createLoanMutation = trpc.loans.create.useMutation()

  useEffect(() => {
    if (accountId) {
      setSelectedAccountId(accountId)
    }
  }, [accountId])

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const formData = new FormData(e.currentTarget)

    try {
      await createLoanMutation.mutateAsync({
        account_id: selectedAccountId,
        principal_amount: parseFloat(formData.get('principal_amount') as string),
        interest_rate: parseFloat(formData.get('interest_rate') as string),
        tenure_months: parseInt(formData.get('tenure_months') as string),
        payment_frequency: formData.get('payment_frequency') as 'bi-monthly' | 'monthly' | 'weekly',
        start_date: formData.get('start_date') as string,
      })

      router.push('/loans')
    } catch (error) {
      console.error('Failed to create loan:', error)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="light" onPress={() => router.back()}>
          ← Back
        </Button>
        <h1 className="text-3xl font-bold">Create Loan</h1>
      </div>

      <Card className="max-w-2xl">
        <CardHeader>
          <h2 className="text-xl font-semibold">Loan Details</h2>
        </CardHeader>
        <CardBody>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Select
              label="Account"
              placeholder="Select account"
              isRequired
              selectedKeys={selectedAccountId ? [selectedAccountId] : []}
              onSelectionChange={(keys) => {
                const value = Array.from(keys)[0] as string
                setSelectedAccountId(value)
              }}
              variant="bordered"
              labelPlacement="outside"
            >
              {(accounts ?? []).map((account) => (
                <SelectItem key={account.id}>
                  {account.name}
                </SelectItem>
              ))}
            </Select>

            <Input
              label="Principal Amount"
              name="principal_amount"
              type="number"
              step="0.01"
              min="0"
              required
              variant="bordered"
              labelPlacement="outside"
            />

            <Input
              label="Interest Rate (%)"
              name="interest_rate"
              type="number"
              step="0.01"
              min="0"
              max="100"
              required
              variant="bordered"
              labelPlacement="outside"
            />

            <Input
              label="Tenure (months)"
              name="tenure_months"
              type="number"
              min="1"
              required
              variant="bordered"
              labelPlacement="outside"
            />

            <Select
              label="Payment Frequency"
              name="payment_frequency"
              placeholder="Select frequency"
              isRequired
              variant="bordered"
              labelPlacement="outside"
            >
              <SelectItem key="bi-monthly">
                Bi-Monthly (Every 15 days)
              </SelectItem>
              <SelectItem key="monthly">
                Monthly
              </SelectItem>
              <SelectItem key="weekly">
                Weekly
              </SelectItem>
            </Select>

            <Input
              label="Start Date"
              name="start_date"
              type="date"
              required
              variant="bordered"
              labelPlacement="outside"
            />

            <div className="flex gap-4 justify-end pt-4">
              <Button type="button" variant="light" onPress={() => router.back()}>
                Cancel
              </Button>
              <Button
                type="submit"
                color="primary"
                isLoading={createLoanMutation.isPending}
              >
                Create Loan
              </Button>
            </div>
          </form>
        </CardBody>
      </Card>
    </div>
  )
}

// pages/loans/create.vue
<template>
  <v-container>
    <v-row justify="center">
      <v-col cols="12" lg="10">
        <v-card>
          <v-card-title class="d-flex align-center">
            <v-btn icon variant="text" @click="$router.back()">
              <v-icon>mdi-arrow-left</v-icon>
            </v-btn>
            <span class="ml-2">Create New Loan</span>
          </v-card-title>

          <v-divider />

          <v-card-text class="pt-6">
            <v-form ref="formRef" v-model="formValid" @submit.prevent="handleSubmit">
              <v-row>
                <!-- Loan Details -->
                <v-col cols="12" md="6">
                  <h3 class="text-h6 mb-4">
                    Loan Details
                  </h3>

                  <v-select
                    v-model="form.account_id"
                    :items="accountOptions"
                    item-title="name"
                    item-value="id"
                    label="Select Account *"
                    prepend-inner-icon="mdi-account"
                    :rules="[rules.required]"
                    variant="outlined"
                    class="mb-4"
                    :loading="accountsStore.loading"
                  />

                  <v-text-field
                    v-model.number="form.principal_amount"
                    label="Principal Amount *"
                    type="number"
                    prepend-inner-icon="mdi-cash"
                    :rules="[rules.required, rules.positive]"
                    variant="outlined"
                    class="mb-4"
                    autocomplete="off"
                  />

                  <div class="mb-4">
                    <v-slider
                      v-model="form.interest_rate"
                      :min="3"
                      :max="5"
                      :step="0.5"
                      thumb-label
                      class="mb-2"
                    >
                      <template #prepend>
                        <span class="text-body-2">3%</span>
                      </template>
                      <template #append>
                        <span class="text-body-2">5%</span>
                      </template>
                    </v-slider>
                    <v-text-field
                      v-model.number="form.interest_rate"
                      label="Interest Rate (% per month) *"
                      type="number"
                      prepend-inner-icon="mdi-percent"
                      :rules="[rules.required, rules.interestRate]"
                      variant="outlined"
                      suffix="%"
                      autocomplete="off"
                    />
                  </div>

                  <v-select
                    v-model="form.tenure_months"
                    :items="tenureOptions"
                    label="Tenure (Months) *"
                    prepend-inner-icon="mdi-calendar"
                    :rules="[rules.required]"
                    variant="outlined"
                    class="mb-4"
                  />

                  <v-select
                    v-model="form.payment_frequency"
                    :items="frequencyOptions"
                    item-title="label"
                    item-value="value"
                    label="Payment Frequency *"
                    prepend-inner-icon="mdi-calendar-clock"
                    :rules="[rules.required]"
                    variant="outlined"
                    class="mb-4"
                  />

                  <v-text-field
                    v-model="form.start_date"
                    label="Start Date"
                    type="date"
                    prepend-inner-icon="mdi-calendar-start"
                    variant="outlined"
                    hint="Leave empty to use approval date"
                    autocomplete="off"
                  />
                </v-col>

                <!-- Amortization Preview -->
                <v-col cols="12" md="6">
                  <h3 class="text-h6 mb-4">
                    Amortization Preview
                  </h3>

                  <v-card variant="outlined" class="mb-4">
                    <v-card-text>
                      <div class="d-flex justify-space-between mb-2">
                        <span class="text-grey">Total Amount:</span>
                        <span class="font-weight-bold">{{ formatCurrency(totalAmount) }}</span>
                      </div>
                      <div class="d-flex justify-space-between mb-2">
                        <span class="text-grey">Total Interest:</span>
                        <span class="font-weight-bold text-warning">{{ formatCurrency(totalInterest) }}</span>
                      </div>
                      <div class="d-flex justify-space-between">
                        <span class="text-grey">Number of Payments:</span>
                        <span class="font-weight-bold">{{ schedulePreview.length }}</span>
                      </div>
                    </v-card-text>
                  </v-card>

                  <div v-if="schedulePreview.length > 0" style="max-height: 400px; overflow-y: auto;">
                    <v-table density="compact">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Due Date</th>
                          <th>Amount</th>
                          <th>Balance</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr v-for="item in schedulePreview" :key="item.payment_number">
                          <td>{{ item.payment_number }}</td>
                          <td>{{ formatDate(item.due_date) }}</td>
                          <td>{{ formatCurrency(item.total_due) }}</td>
                          <td>{{ formatCurrency(item.remaining_balance) }}</td>
                        </tr>
                      </tbody>
                    </v-table>
                  </div>
                </v-col>
              </v-row>

              <v-alert v-if="error" type="error" variant="tonal" class="mb-4 mt-4">
                {{ error }}
              </v-alert>

              <v-alert v-if="success" type="success" variant="tonal" class="mb-4 mt-4">
                Loan created successfully! Pending admin approval.
              </v-alert>

              <v-divider class="my-4" />

              <div class="d-flex gap-2">
                <v-btn
                  type="submit"
                  color="primary"
                  size="large"
                  :loading="loading"
                  :disabled="!formValid || !canSubmit"
                >
                  Create Loan
                </v-btn>
                <v-btn
                  variant="outlined"
                  size="large"
                  :disabled="loading"
                  @click="$router.back()"
                >
                  Cancel
                </v-btn>
              </div>
            </v-form>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { formatCurrency, formatDate } from '~/utils/formatters'
import type { PaymentFrequency } from '~/types'

export default defineComponent({
  name: 'LoansCreate',

  data () {
    return {
      formRef: null as any,
      formValid: false,
      loading: false,
      error: '',
      success: false,
      form: {
        account_id: (this.$route.query.account_id as string) || '',
        principal_amount: 0,
        interest_rate: 3.5,
        tenure_months: 6,
        payment_frequency: 'monthly' as PaymentFrequency,
        start_date: ''
      },
      tenureOptions: Array.from({ length: 11 }, (_, i) => ({
        title: `${i + 2} months`,
        value: i + 2
      })),
      frequencyOptions: [
        { label: 'Bi-Monthly (Every 15 days)', value: 'bi-monthly' },
        { label: 'Monthly', value: 'monthly' },
        { label: 'Weekly', value: 'weekly' }
      ],
      rules: {
        required: (v: any) => !!v || 'This field is required',
        positive: (v: number) => v > 0 || 'Must be greater than 0',
        interestRate: (v: number) => (v >= 3 && v <= 5) || 'Interest rate must be between 3% and 5%'
      }
    }
  },

  computed: {
    accountsStore () {
      return useAccountsStore()
    },

    loansStore () {
      return useLoansStore()
    },

    uiStore () {
      return useUIStore()
    },

    accountOptions () {
      return this.accountsStore.accounts
    },

    schedulePreview () {
      return this.loansStore.generateSchedulePreview(this.form)
    },

    totalInterest () {
      return this.schedulePreview.reduce((sum, item) => sum + item.interest_due, 0)
    },

    totalAmount () {
      return this.form.principal_amount + this.totalInterest
    },

    canSubmit () {
      return this.form.account_id && this.form.principal_amount > 0
    }
  },

  async mounted () {
    try {
      await this.accountsStore.fetchAccounts()
    } catch (error: any) {
      this.uiStore.showError('Failed to load accounts')
    }
  },

  methods: {
    formatCurrency,
    formatDate,

    async handleSubmit () {
      if (!this.formRef) { return }

      const { valid } = await this.formRef.validate()
      if (!valid) { return }

      this.loading = true
      this.error = ''
      this.success = false

      const result = await this.loansStore.createLoan(this.form)

      if (result.success) {
        this.success = true
        this.uiStore.showSuccess('Loan created and pending approval')
        setTimeout(() => {
          this.$router.push('/loans')
        }, 2000)
      } else {
        this.error = result.error || 'Failed to create loan'
        this.uiStore.showError(this.error)
      }

      this.loading = false
    }
  }
})

definePageMeta({
  middleware: 'auth'
})
</script>
